'use client';
import {useEffect,useState} from 'react';
import type {Question} from '@/lib/questions';
import './admin.css';
type Plan={day:string;question:Question;image:string};
type Daily={day:string;visitors?:number;views?:number;votes?:number;comments?:number};
type Data={counts:{members:number;voters:number;votes:number;comments:number;reported:number;hidden:number};today:string;currentDay:string;visits:Daily[];dailyVotes:Daily[];dailyComments:Daily[];current:{question:Question;image:string};templates:Question[];templateImages:string[];plans:Plan[]};
type Comment={id:string;day:string;name:string;body:string;created:string;parent:string|null;choice:number;hidden:number;reports:number};
const fields=[['tag','분류'],['title','질문'],['options.0','A 선택지'],['options.1','B 선택지'],['sub.0','A 부연 설명'],['sub.1','B 부연 설명'],['story','숫자 뒤에 있는 이야기'],['arguments.0','A 선택 이유'],['arguments.1','B 선택 이유'],['knowledge','오늘의 생각 도구'],['prompt','조건 변경 질문'],['insight.0','A를 선택한 나'],['insight.1','B를 선택한 나']] as const;
function pair(q:Question,path:string):[string,string]{const [key,index]=path.split('.');const v=q[key as keyof Question];return (index===undefined?v:v[Number(index)]) as [string,string]}
function tomorrow(day:string){return new Date(Date.parse(day+'T00:00:00Z')+86400000).toISOString().slice(0,10)}
export default function Dashboard({email}:{email:string}){
 const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState('overview'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[comments,setComments]=useState<Comment[]>([]),[next,setNext]=useState<string|null>(null),[filter,setFilter]=useState('all'),[draft,setDraft]=useState<Question|null>(null),[day,setDay]=useState(''),[image,setImage]=useState('/images/topic-0.webp'),[language,setLanguage]=useState<0|1>(0);
 async function load(){setError('');try{const r=await fetch('/api/admin',{cache:'no-store'}),v=await r.json() as Data & {error?:string};if(!r.ok)throw Error(v.error);setData(v);setDraft(old=>old||structuredClone(v.templates[0]));setDay(old=>old||tomorrow(v.currentDay))}catch(e){setError((e as Error).message)}}
 useEffect(()=>{load()},[]);
 async function loadComments(more=false,selected=filter){setBusy(true);setError('');try{const params=new URLSearchParams({section:'comments',filter:selected});if(more&&next)params.set('before',next);const r=await fetch('/api/admin?'+params,{cache:'no-store'}),v=await r.json() as {items:Comment[];next:string|null;error?:string};if(!r.ok)throw Error(v.error);setComments(old=>more?[...old,...v.items.filter((c:Comment)=>!old.some(x=>x.id===c.id))]:v.items);setNext(v.next)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function act(body:unknown){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),v=await r.json() as {error?:string};if(!r.ok)throw Error(v.error);return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 function edit(path:string,value:string){if(!draft)return;const q=structuredClone(draft);pair(q,path)[language]=value;setDraft(q)}
 function selectTemplate(index:number){if(!data)return;setDraft(structuredClone(data.templates[index]));setImage(data.templateImages[index])}
 const today=data?.visits.find(r=>r.day===data.today);
 const days=data?Array.from({length:14},(_,i)=>new Date(Date.parse(data.today+'T00:00:00Z')-(13-i)*86400000).toISOString().slice(0,10)):[];
 return <main className="admin-main"><header className="admin-head"><div><span className="admin-kicker">COMMUNITY / ADMIN</span><h1>내 커뮤니티 관리</h1><p>{email}</p></div><div><a href="/">홈페이지 보기 ↗</a><button disabled={busy} onClick={load}>새로고침</button></div></header>
 <nav className="admin-tabs" aria-label="관리 메뉴">{[['overview','방문·참여 현황'],['comments','댓글 관리'],['topics','주제 예약']].map(([id,name])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setNotice('');if(id==='comments')loadComments()}}>{name}</button>)}</nav>
 {error&&<div className="admin-error" role="alert">{error}<button onClick={load}>다시 시도</button></div>}{notice&&<p className="admin-notice" role="status">{notice}</p>}{!data&&!error&&<p>관리 정보를 불러오는 중…</p>}
 {data&&tab==='overview'&&<><div className="admin-cards">{[['등록 회원',data.counts.members],['오늘 방문 브라우저',today?.visitors||0],['오늘 페이지 조회',today?.views||0],['누적 투표',data.counts.votes],['댓글·답글',data.counts.comments],['신고된 글',data.counts.reported]].map(([label,n])=><article key={label}><span>{label}</span><strong>{Number(n).toLocaleString()}</strong></article>)}</div>
 <section className="admin-panel"><h2>최근 14일</h2><p>한국 시간 자정 기준입니다. 방문 통계는 이번 기능 설치 이후부터 집계됩니다. 브라우저·쿠키 기준이므로 실제 사람 수와 다르며, 관리 화면 방문은 제외합니다.</p><div className="admin-table"><table><thead><tr><th>날짜</th><th>방문 브라우저</th><th>페이지 조회</th><th>투표</th><th>댓글·답글</th></tr></thead><tbody>{days.map(d=>{const v=data.visits.find(r=>r.day===d);return <tr key={d}><td>{d}</td><td>{v?.visitors??'—'}</td><td>{v?.views??'—'}</td><td>{data.dailyVotes.find(r=>r.day===d)?.votes||0}</td><td>{data.dailyComments.find(r=>r.day===d)?.comments||0}</td></tr>})}</tbody></table></div><p>등록 회원은 프로필 등록을 마친 현재 회원 수입니다. 누적 투표·댓글 수는 탈퇴 시 삭제 또는 익명 처리된 기록을 제외합니다.</p></section><section className="admin-panel"><h2>현재 질문</h2><p>{data.current.question.title[0]}</p><small>{data.currentDay} 오전 9시부터 다음 날 오전 9시까지</small></section></>}
 {data&&tab==='comments'&&<section className="admin-panel"><div className="admin-row"><h2>댓글·답글 관리</h2><select aria-label="댓글 필터" value={filter} disabled={busy} onChange={e=>{setFilter(e.target.value);loadComments(false,e.target.value)}}><option value="all">전체</option><option value="reported">신고된 글</option><option value="hidden">관리자가 숨긴 글</option></select></div><p>숨김은 공개 화면에서 글과 그 아래 답글을 가립니다. 복원할 수 있습니다. 신고 3회로 숨겨진 글은 관리자 숨김을 복원해도 계속 숨겨집니다.</p>{!comments.length&&!busy&&<p>해당하는 댓글이 없습니다.</p>}{comments.map(c=><article className="admin-comment" key={c.id}><div className="admin-row"><strong>{c.name} · {c.choice===0?'A':'B'} {c.parent?'· 답글':''}</strong><span>신고 {c.reports}회 {c.hidden?'· 관리자 숨김':''}</span></div><small>{c.day} 질문 · {new Date(c.created).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</small><p>{c.body}</p><button disabled={busy} onClick={async()=>{if(await act({action:c.hidden?'restore':'hide',id:c.id})){setNotice(c.hidden?'댓글을 복원했어요.':'댓글을 숨겼어요.');await loadComments();await load()}}}>{c.hidden?'복원하기':'공개 화면에서 숨기기'}</button></article>)}{next&&<button disabled={busy} onClick={()=>loadComments(true)}>댓글 더보기</button>}</section>}
 {data&&draft&&tab==='topics'&&<><section className="admin-panel"><h2>새 주제 예약</h2><p>선택한 날짜의 한국 시간 오전 9시에 공개됩니다. 오늘과 지난 질문은 기록 보호를 위해 변경하지 않습니다. 예약이 없는 날은 10월 6일 오전 9시부터 새 질문 100개가 순서대로 순환합니다.</p><div className="admin-form-grid"><label>공개 날짜<input type="date" required min={tomorrow(data.currentDay)} value={day} onChange={e=>setDay(e.target.value)}/></label><label>기존 질문을 바탕으로 작성<select defaultValue="0" onChange={e=>selectTemplate(Number(e.target.value))}>{data.templates.map((q,index)=><option key={index} value={index}>{index+1}. {q.title[0].slice(0,40)}</option>)}</select></label></div><div className="admin-row"><button aria-pressed={language===0} onClick={()=>setLanguage(0)}>한국어 원고</button><button aria-pressed={language===1} onClick={()=>setLanguage(1)}>영어 원고</button></div><p>한국어·영어 내용을 모두 확인해 주세요. 날짜를 바꿔 여러 주제를 계속 예약할 수 있습니다.</p><div className="admin-form-grid">{fields.map(([path,label])=><label key={path}>{label}<textarea rows={['story','knowledge'].includes(path)?4:2} maxLength={path==='story'?3000:1500} value={pair(draft,path)[language]} onChange={e=>edit(path,e.target.value)}/></label>)}</div><label>주제 이미지<select value={image} onChange={e=>setImage(e.target.value)}>{data.templateImages.map((path,index)=><option key={path} value={path}>{index+1}. {data.templates[index].tag[0]} · {data.templates[index].title[0].slice(0,22)}</option>)}</select></label><img className="admin-topic-image" src={image} alt="선택한 주제 이미지"/><details><summary>공개 원고 미리보기</summary><h3>{draft.title[language]}</h3><p>A · {draft.options[0][language]}</p><p>B · {draft.options[1][language]}</p><p>{draft.story[language]}</p></details><button className="admin-primary" disabled={busy||!day} onClick={async()=>{if(await act({action:'schedule',day,question:draft,image})){setNotice(`${day} 오전 9시 주제를 예약했어요.`);await load()}}}>{busy?'저장 중…':'이 날짜에 예약하기'}</button></section>
 <section className="admin-panel"><h2>예약된 주제</h2>{!data.plans.length&&<p>아직 예약된 주제가 없습니다.</p>}{data.plans.map(p=><article className="admin-comment" key={p.day}><strong>{p.day} 오전 9시</strong><p>{p.question.title[0]}</p>{p.day>data.currentDay?<div className="admin-row"><button disabled={busy} onClick={()=>{setDraft(structuredClone(p.question));setDay(p.day);setImage(p.image);setNotice('원고를 불러왔어요. 수정 후 예약하기를 누르면 반영돼요.');window.scrollTo({top:0,behavior:'smooth'})}}>불러와서 수정</button><button disabled={busy} onClick={async()=>{if(await act({action:'cancel',day:p.day})){setNotice('예약을 취소했어요. 이날은 기본 순환 질문이 나옵니다.');await load()}}}>예약 취소</button></div>:<small>공개 완료 · 수정 불가</small>}</article>)}</section></>}
 </main>
}
