'use client';
import { useEffect,useRef,useState } from 'react';
import { Heart, MessageCircle, Sparkles, Flag, X, Check, ChevronDown } from 'lucide-react';
import { regions } from '@/lib/community';
import Mascot from './mascot';
import type { Lang } from '@/lib/questions';
type Comment={id:string;choice:number;country:string;name:string;body:string;parent:string|null;created:string;likes:number;persuaded:number;liked:number;convinced:number;mine:number;replyCount:number};
type Page={best?:Comment[];items:Comment[];nextCursor:string|null;error?:string};
type Props={signedIn:boolean;day:string;lang:Lang;ownChoice:number;nickname:string;busy:boolean;actionError:string;act:(action:Record<string,unknown>)=>Promise<boolean>;onToast:(text:string)=>void};
export default function Discussion({signedIn,day,lang,ownChoice,nickname,busy,actionError,act,onToast}:Props){
 const [side,setSide]=useState('all'),[items,setItems]=useState<Comment[]>([]),[best,setBest]=useState<Comment[]>([]),[cursor,setCursor]=useState<string|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[threads,setThreads]=useState<Record<string,Page>>({}),[threadLoading,setThreadLoading]=useState<string|null>(null),[body,setBody]=useState(''),[reply,setReply]=useState<Comment|null>(null);
 const draftKey='community_comment_draft:'+day;
 const generation=useRef(0),i=lang==='ko'?0:1,t=(ko:string,en:string)=>i===0?ko:en;
 async function fetchPage(which:string,after:string|null,parent?:string){const params=new URLSearchParams({day,side:which});if(after)params.set('cursor',after);if(parent)params.set('parent',parent);const r=await fetch('/api/comments?'+params);const p=await r.json() as Page;if(!r.ok)throw Error(p.error||'Please try again');return p}
 async function load(reset=false,which=side){const ticket=reset?++generation.current:generation.current;setLoading(true);setError('');if(reset){setItems([]);setBest([]);setCursor(null);setThreads({})}try{const p=await fetchPage(which,reset?null:cursor);if(generation.current!==ticket)return;setItems(old=>reset?p.items:[...old,...p.items.filter(c=>!old.some(x=>x.id===c.id))]);setCursor(p.nextCursor);setBest(p.best||[])}catch(e){if(generation.current===ticket)setError((e as Error).message)}finally{if(generation.current===ticket)setLoading(false)}}
 useEffect(()=>{try{const saved=sessionStorage.getItem(draftKey);if(saved){const draft=JSON.parse(saved);if(typeof draft.body==='string')setBody(draft.body.slice(0,600));if(draft.reply?.id)setReply(draft.reply)}}catch{}},[day]);
 useEffect(()=>{load(true,side);return()=>{generation.current++}},[side,day]);
 async function loadReplies(id:string,reset=false){setThreadLoading(id);setError('');try{const p=await fetchPage(side,reset?null:threads[id]?.nextCursor||null,id);setThreads(old=>({...old,[id]:{items:reset?p.items:[...(old[id]?.items||[]),...p.items.filter(c=>!old[id]?.items.some(x=>x.id===c.id))],nextCursor:p.nextCursor}}))}catch(e){setError((e as Error).message)}finally{setThreadLoading(null)}}
 function updateComment(id:string,fn:(c:Comment)=>Comment|null){setBest(old=>old.map(c=>c.id===id?fn(c):c).filter((c):c is Comment=>c!==null));setItems(old=>old.map(c=>c.id===id?fn(c):c).filter((c):c is Comment=>c!==null));setThreads(old=>Object.fromEntries(Object.entries(old).map(([key,p])=>[key,{...p,items:p.items.map(c=>c.id===id?fn(c):c).filter((c):c is Comment=>c!==null)}])))}
 async function react(c:Comment,kind:'like'|'persuaded'|'report'){if(await act({action:'reaction',comment:c.id,kind})){updateComment(c.id,row=>kind==='report'?null:kind==='like'?{...row,liked:row.liked?0:1,likes:row.likes+(row.liked?-1:1)}:{...row,convinced:row.convinced?0:1,persuaded:row.persuaded+(row.convinced?-1:1)});if(kind==='report')onToast(t('신고했으며 나에게 숨겼습니다.','Reported and hidden.'));const ticket=generation.current;try{const page=await fetchPage(side,null);if(ticket===generation.current)setBest(page.best||[])}catch{}}}
 function renderComment(c:Comment,nested=false){const r=regions.find(r=>r[0]===c.country);return <article className={'comment '+(nested?'nested':'')} key={c.id}><div className="comment-top"><span className={'avatar side'+c.choice}><Mascot side={c.choice}/></span><div><strong>{c.name}</strong><small>{r?.[1]} {r?.[i+2]} · {t('선택','Choice')} {c.choice===0?'A':'B'}{c.mine?' · '+t('내 의견','You'):''} · {new Date(c.created).toLocaleTimeString(lang==='ko'?'ko-KR':'en-US',{hour:'2-digit',minute:'2-digit'})}</small></div><button className="report" aria-label={t('신고하고 숨기기','Report and hide')} disabled={busy} onClick={()=>react(c,'report')}><Flag size={15}/></button></div><p>{c.body}</p><div className="comment-actions"><a className="thread-link" href={'/thread?id='+encodeURIComponent(c.parent||c.id)}>{t('토론으로 가기','Open thread')} ↗</a><button aria-pressed={!!c.liked} disabled={busy} onClick={()=>react(c,'like')}><Heart size={16} fill={c.liked?'currentColor':'none'}/>{c.likes} {t('공감','Agree')}</button>{ownChoice>=0&&c.choice!==ownChoice&&!c.mine&&<button aria-pressed={!!c.convinced} disabled={busy} onClick={()=>react(c,'persuaded')}><Sparkles size={16}/>{c.persuaded} {t('설득됐어요','Persuaded')}</button>}<button disabled={busy} aria-label={t(`${c.name}님에게 답글 쓰기`,`Reply to ${c.name}`)} onClick={()=>{setReply(c);document.getElementById('comment-input')?.focus()}}><MessageCircle size={16}/>{t('답글 쓰기','Reply')}</button>{!nested&&c.replyCount>0&&<button disabled={threadLoading===c.id} onClick={()=>threads[c.id]?setThreads(old=>{const next={...old};delete next[c.id];return next}):loadReplies(c.id,true)}>{threads[c.id]?t('답글 접기','Hide replies'):t(`답글 ${c.replyCount}개 보기`,`View ${c.replyCount} replies`)}<ChevronDown size={14}/></button>}</div>{!nested&&threads[c.id]?.items.map(x=>renderComment(x,true))}{!nested&&threads[c.id]?.nextCursor&&<button className="reply-more" disabled={threadLoading===c.id} onClick={()=>loadReplies(c.id)}>{threadLoading===c.id?t('불러오는 중…','Loading…'):t('답글 10개 더보기','Show 10 more replies')}</button>}</article>}
 return <section className="discussion" id="discussion"><div className="section-heading"><div><span className="eyebrow">02 / MANY VOICES</span><h2>{t('당신은 왜 그렇게 생각했나요?','Why did you choose that?')}</h2></div><MessageCircle size={25}/></div><p className="section-sub">{t('사람이 아닌 의견에 답해주세요. 다른 생각을 듣는 것도 하나의 발견입니다.','Respond to ideas, not people. A different view is another discovery.')}</p><div className="comment-toolbar"><div className="comment-filters">{[['all','전체','All'],['0','A만','A only'],['1','B만','B only']].map(r=><button key={r[0]} className={side===r[0]?'selected':''} aria-pressed={side===r[0]} onClick={()=>setSide(r[0])}>{r[i+1]}</button>)}</div><small>{t('최신순 · 10개씩','Newest · 10 at a time')}</small></div>
 <form className="comment-form" onSubmit={async e=>{e.preventDefault();try{sessionStorage.setItem(draftKey,JSON.stringify({body,reply}))}catch{}const parent=reply?(reply.parent||reply.id):null;if(await act({action:'comment',body,parent})){setBody('');setReply(null);try{sessionStorage.removeItem(draftKey)}catch{}if(parent){updateComment(parent,c=>({...c,replyCount:c.replyCount+1}));await loadReplies(parent,true)}else if(side!=='all'&&side!==String(ownChoice))setSide('all');else await load(true);onToast(parent?t('답글을 남겼어요.','Your reply is posted.'):t('당신의 이유를 남겼어요.','Your reason is posted.'))}}}>{reply&&<div className="reply-label">{reply.name}{t('님에게 답글',' · reply')}<button type="button" onClick={()=>setReply(null)} aria-label={t('답글 취소','Cancel reply')}><X size={15}/></button></div>}<div className="comment-member"><strong>{nickname||t(signedIn?'닉네임을 설정해 주세요':'방문자',signedIn?'Set your nickname':'Guest')}</strong>{signedIn&&<a href="/profile?return_to=comment">{t(nickname?'닉네임 수정':'닉네임 설정',nickname?'Edit nickname':'Set nickname')}</a>}</div><textarea id="comment-input" aria-label={t('내 선택의 이유','Reason for your choice')} placeholder={reply?t(`${reply.name}님의 의견에 대한 내 생각은…`,`My response to ${reply.name}…`):t('나는 이쪽을 골랐어요. 그 이유는…','I chose this because…')} minLength={3} maxLength={600} value={body} onChange={e=>{setBody(e.target.value);try{sessionStorage.setItem(draftKey,JSON.stringify({body:e.target.value,reply}))}catch{}}} required/><div><small>{body.length}/600 · {t('원문 그대로 표시됩니다','Shown in the original language')}</small><button className="primary" type={signedIn?'submit':'button'} onClick={signedIn?undefined:()=>{try{sessionStorage.setItem(draftKey,JSON.stringify({body,reply}))}catch{}act({action:'signin'})}} disabled={busy||(signedIn&&body.trim().length<3)}>{busy?t('저장 중…','Saving…'):!signedIn?t('로그인하고 댓글 남기기','Sign in to post'):reply?t('답글 남기기','Post reply'):t('이유 남기기','Post my reason')}</button></div>{actionError&&<p className="comment-error" role="alert">{actionError}</p>}</form>
 <div className="best-comments"><h3>★ {t('베스트 댓글','Best comments')}</h3>{best.length?best.map(c=><div key={'best-'+c.id}><span className="best-comment-label">BEST</span>{renderComment(c)}</div>):<p>{t('공감을 받은 댓글이 생기면 여기에서 먼저 보여드려요.','Comments with agreement will appear here first.')}</p>}<p>{t('공감순 · 최대 3개 · 신고·숨김 글 제외','Most agreement · up to 3 · hidden and reported comments excluded')}</p></div><h3 className="latest-comments-label">{t('최신 댓글','Latest comments')}</h3>
 {items.map(c=>renderComment(c))}
 {error&&<div className="comment-error" role="alert">{error}<button onClick={()=>load(items.length===0)}>{t('다시 시도','Try again')}</button></div>}
 {!items.length&&!loading&&!error&&<div className="empty-comments"><MessageCircle size={27}/><h3>{t('첫 번째 이야기를 기다려요.','The first story is still unwritten.')}</h3><p>{t('당신의 이유가 다른 사람에게 새로운 관점이 될 수 있어요.','Your reason could give someone a new perspective.')}</p></div>}
 {loading&&!items.length&&<p className="comment-loading" role="status">{t('의견을 불러오고 있어요.','Loading perspectives…')}</p>}
 {(cursor||loading&&items.length>0)&&<div className="comments-more"><button disabled={loading} onClick={()=>load()}>{loading?t('불러오는 중…','Loading…'):t('댓글 10개 더보기','Show 10 more comments')}<ChevronDown size={17}/></button><small>{t(`현재 ${items.length}개의 의견을 보고 있어요.`,`Showing ${items.length} perspectives.`)}</small></div>}
 </section>
}
