'use client';
import {useEffect,useRef,useState} from 'react';
import './install-notifications.css';
type InstallEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
type Config={signedIn:boolean;publicKey:string;error?:string};
const fromBase64=(value:string)=>Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
export default function InstallNotifications(){
 const [config,setConfig]=useState<Config|null>(null),[installed,setInstalled]=useState(false),[ios,setIos]=useState(false),[supported,setSupported]=useState(false),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[dialog,setDialog]=useState<'install'|'push'|null>(null),[message,setMessage]=useState('');const install=useRef<InstallEvent|null>(null),panel=useRef<HTMLDivElement>(null),trigger=useRef<HTMLElement|null>(null);
 async function request(body:unknown){const response=await fetch('/api/push',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json() as {ok?:boolean;active?:boolean;error?:string};if(!response.ok)throw Error(data.error||'다시 시도해 주세요.');return data}
 useEffect(()=>{setIos(/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1));const media=window.matchMedia('(display-mode: standalone)'),standalone=()=>setInstalled(media.matches||!!(navigator as Navigator&{standalone?:boolean}).standalone);standalone();media.addEventListener('change',standalone);const capture=(e:Event)=>{e.preventDefault();install.current=e as InstallEvent},done=()=>{setInstalled(true);install.current=null};window.addEventListener('beforeinstallprompt',capture);window.addEventListener('appinstalled',done);const capable='serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window;setSupported(capable);let live=true;(async()=>{try{const r=await fetch('/api/push',{cache:'no-store'});const data=await r.json() as Config;if(!r.ok)throw Error(data.error);if(live)setConfig(data);if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.register('/community-sw.js',{scope:'/',updateViaCache:'none'});if(capable&&data.signedIn){const sub=await reg.pushManager.getSubscription();if(sub){const status=await request({action:'status',subscription:sub.toJSON()});if(live)setEnabled(!!status.active)}}}}catch{}})();return()=>{live=false;media.removeEventListener('change',standalone);window.removeEventListener('beforeinstallprompt',capture);window.removeEventListener('appinstalled',done)}},[]);
 useEffect(()=>{if(!dialog)return;const prev=document.activeElement as HTMLElement;trigger.current=prev;panel.current?.focus();function keys(e:KeyboardEvent){if(e.key==='Escape')setDialog(null);if(e.key==='Tab'){const focusable=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href]');if(!focusable?.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}document.addEventListener('keydown',keys);return()=>{document.removeEventListener('keydown',keys);prev?.focus()}},[dialog]);
 async function add(){setMessage('');if(install.current){try{await install.current.prompt();const result=await install.current.userChoice;if(result.outcome==='accepted')setMessage('홈 화면에 추가하고 있어요.');install.current=null}catch{setDialog('install')}}else setDialog('install')}
 async function enable(){setMessage('');if(!config?.signedIn){setMessage('구글 로그인 후 알림을 켜 주세요.');return}if(ios&&!installed){setDialog('install');setMessage('아이폰은 먼저 홈 화면에 추가한 뒤, 그 아이콘으로 열어서 알림을 켜 주세요.');return}if(!supported){setMessage('이 앱에서는 알림을 지원하지 않아요. 사파리 또는 크롬에서 열어 주세요.');return}setBusy(true);try{const permission=await Notification.requestPermission();if(permission!=='granted'){setMessage('알림이 허용되지 않았어요. 휴대폰·브라우저 설정에서 허용한 뒤 다시 시도해 주세요.');return}const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:fromBase64(config.publicKey)});await request({action:'subscribe',subscription:sub.toJSON()});setEnabled(true);setMessage('답글 알림을 켰어요. 테스트 알림으로 확인해 보세요.')}catch(e){setMessage(e instanceof Error?e.message:'알림 연결에 실패했어요. 다시 시도해 주세요.')}finally{setBusy(false)}}
 async function disable(){setBusy(true);try{const reg=await navigator.serviceWorker.ready,sub=await reg.pushManager.getSubscription();if(sub){await request({action:'unsubscribe',subscription:sub.toJSON()});await sub.unsubscribe()}setEnabled(false);setMessage('이 기기의 답글 알림을 껐어요.')}catch{setMessage('알림 해제에 실패했어요. 다시 시도해 주세요.')}finally{setBusy(false)}}
 return <><div className="community-app-tools" aria-label="커뮤니티 설치와 알림"><a href="/notifications" className="app-tool-link">♧ 내 답글 알림</a><div><button onClick={add} disabled={installed}>{installed?'✓ 홈 화면에서 사용 중':'＋ 홈 화면에 추가'}</button><button onClick={()=>{setMessage('');setDialog('push')}}>♧ {enabled?'답글 알림 켜짐':'답글 알림 켜기'}</button></div></div>
 {dialog&&<div className="app-dialog-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)setDialog(null)}}><div ref={panel} tabIndex={-1} className="app-dialog" role="dialog" aria-modal="true" aria-labelledby="app-dialog-title"><button className="app-dialog-close" aria-label="닫기" disabled={busy} onClick={()=>setDialog(null)}>×</button><img src="/icons/community-192.png" width={72} height={72} alt="커뮤니티 아이콘"/><h2 id="app-dialog-title">{dialog==='install'?'다음엔 아이콘으로 바로 만나요':'내 의견에 답이 오면 알려드릴게요'}</h2>
 {dialog==='install'?<><p>앱스토어 없이 휴대폰 홈 화면에 커뮤니티를 추가할 수 있어요.</p>{ios?<ol><li>브라우저의 <strong>공유 버튼</strong>을 누르세요.</li><li><strong>홈 화면에 추가</strong>를 선택하세요.</li><li><strong>추가</strong>를 누른 뒤 생긴 커뮤니티 아이콘을 열어 주세요.</li></ol>:<ol><li>브라우저 메뉴 <strong>⋮</strong>를 누르세요.</li><li><strong>앱 설치</strong> 또는 <strong>홈 화면에 추가</strong>를 선택하세요.</li><li>설치를 확인하고 커뮤니티 아이콘을 열어 주세요.</li></ol>}<p className="app-note">메뉴가 없다면 네이버·카톡의 ‘다른 브라우저로 열기’를 이용해 사파리나 크롬에서 다시 열어 주세요. 기기와 앱 버전에 따라 메뉴 이름이 다를 수 있어요.</p><button className="app-primary" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'/');setMessage('주소를 복사했어요. 원하는 브라우저 주소창에 붙여 넣어 주세요.')}catch{setMessage(location.origin+'/')}}}>홈페이지 주소 복사</button></>:<><p>다른 사람이 내 댓글에 답글을 남기면 휴대폰 알림으로 알려드려요. 누르면 그 댓글의 토론으로 이동합니다.</p><p className="app-note">아이폰은 홈 화면에 추가한 커뮤니티에서 켜 주세요. 알림 허용은 선택이며 언제든 끌 수 있어요. 매일 새 질문 알림은 아직 보내지 않습니다.</p>{config?.signedIn?<div className="app-dialog-actions"><button className="app-primary" disabled={busy} onClick={enabled?disable:enable}>{busy?'연결 중…':enabled?'이 기기 알림 끄기':'답글 알림 허용하기'}</button>{enabled&&<button disabled={busy} onClick={async()=>{setBusy(true);try{await request({action:'test'});setMessage('테스트 알림을 보냈어요. 잠금 화면이나 알림센터를 확인해 주세요.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>테스트 알림 보내기</button>}</div>:<a className="app-primary" href="/api/auth/google/login?return_to=%2F">구글 로그인하고 연결</a>}</>}
 {message&&<p className="app-feedback" role="status">{message}</p>}</div></div>}{message&&!dialog&&<p className="app-inline-message" role="status">{message}</p>}</>
}
