'use client';
import { useEffect,useState } from 'react';
import { Globe2, ArrowUpRight, Heart, MessageCircle, Sparkles, Bookmark, Share2, Check, X, Flag, RefreshCw, ChevronDown } from 'lucide-react';
import Entrance from './entrance';
import Discussion from './discussion';
import Mascot from './mascot';
import QuestionMood from './question-mood';
import { regions, type Profile } from '@/lib/community';
import { questionFor, type Lang, type Question } from '@/lib/questions';
import type { Member } from '@/lib/member';
type Vote={day:string;choice:number;country:string;reflection:string|null};

type Data={profile:Profile|null;day:string;question:Question;own:Vote|null;totals:{choice:number;n:number}[];regions:{country:string;choice:number;n:number}[];history:Vote[]};
export default function World({member,signInUrl,signOutUrl}:{member:Member|null;signInUrl:string;signOutUrl:string}){
 const [entered,setEntered]=useState(false),[lang,setLang]=useState<Lang>('ko'),[view,setView]=useState('today'),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[country,setCountry]=useState('KR'),[choice,setChoice]=useState<number|null>(null),[toast,setToast]=useState(''),[about,setAbout]=useState(false),[remaining,setRemaining]=useState(''),[resultsDay,setResultsDay]=useState<string|null>(null);
 const i=lang==='ko'?0:1,t=(ko:string,en:string)=>i===0?ko:en,q=data?.question;
 const showResults=!!data?.own&&resultsDay===data.day;
 useEffect(()=>{const saved=localStorage.getItem('ow_lang');if(saved==='en')setLang('en');load(true);},[]);
 useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem('ow_lang',lang)},[lang]);
 useEffect(()=>{const tick=()=>{const now=Date.now(),next=Date.parse(new Date(now).toISOString().slice(0,10)+'T00:00:00Z')+86400000;const s=Math.floor((next-now)/1000);setRemaining(`${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`);if(data&&data.day!==new Date(now).toISOString().slice(0,10))load()};tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[data?.day]);
 useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(id)}},[toast]);
 useEffect(()=>{setChoice(null)},[data?.day]);
 useEffect(()=>{if(!entered||view!=='today')return;window.scrollTo({top:0,behavior:'instant'});document.getElementById(showResults?'results-heading':'question-heading')?.focus({preventScroll:true})},[entered,view,showResults,data?.day]);
 async function load(initial=false){try{setError('');const r=await fetch('/api/world');const v=await r.json() as Data & {error?:string};if(!r.ok)throw Error(v.error);setData(v);if(v.profile)setCountry(v.profile.country);else if(v.own)setCountry(v.own.country);if(initial&&member&&v.profile?.nickname)setEntered(true)}catch(e){setError(e instanceof Error?e.message:'Please try again')}}
 async function act(action:Record<string,unknown>){if(!data||busy)return false;setBusy(true);setError('');try{const r=await fetch('/api/world',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...action,day:data.day})});const v=await r.json() as Data & {error?:string};if(!r.ok)throw Error(v.error);setData(v);return true}catch(e){setError(e instanceof Error?e.message:'Please try again');return false}finally{setBusy(false)}}
 async function share(){const text=q?`${q.title[i].replace('\n',' ')}\n${t('너라면 어느 쪽?','What would you choose?')}`:'';try{if(navigator.share)await navigator.share({title:'커뮤니티',text,url:location.origin});else{await navigator.clipboard.writeText(text+'\n'+location.origin);setToast(t('질문 링크를 복사했어요.','Question link copied.'))}}catch(e){if((e as Error).name!=='AbortError')setToast(t('주소창의 링크를 복사해 공유해 주세요.','Copy the URL from your browser to share.'))}}
 const total=data?.totals.reduce((s,r)=>s+r.n,0)||0,count=(c:number)=>data?.totals.find(r=>r.choice===c)?.n||0,percent=(c:number)=>total?Math.round(count(c)/total*100):0;
 const regionRows=regions.map(r=>{const votes=data?.regions.filter(v=>v.country===r[0])||[],n=votes.reduce((s,v)=>s+v.n,0),a=votes.find(v=>v.choice===0)?.n||0;return {r,n,p:n?Math.round(a/n*100):0}}).filter(r=>r.n>0).sort((a,b)=>b.n-a.n);
 const history=data?.history||[];let streak=0;if(history.length){let cursor=Date.parse((history[0].day===data?.day?data.day:new Date(Date.parse(data!.day)-86400000).toISOString().slice(0,10))+'T00:00:00Z');for(const v of history){if(Date.parse(v.day+'T00:00:00Z')===cursor){streak++;cursor-=86400000}else break}}

 if(!entered)return <Entrance member={member} signInUrl={signInUrl} signOutUrl={signOutUrl} lang={lang} setLang={setLang} profile={data?.profile||null} loading={!data} busy={busy} error={error} onRetry={()=>load()} onEnter={async profile=>{if(await act({action:'profile',...profile})){setCountry(profile.country);setResultsDay(null);setChoice(null);setView('today');setEntered(true)}}}/>;
 return <><header><div className="header-inner"><a className="brand" href="/" aria-label="커뮤니티 홈"><span className="brand-icon"><Mascot/></span>{t('커뮤니티','COMMUNITY')}</a><nav aria-label={t('주 메뉴','Main navigation')}><button className={view==='today'?'active':''} onClick={()=>setView('today')}>{t('오늘의 질문','Today')}</button><button className={view==='history'?'active':''} onClick={()=>setView('history')}>{t('내 선택 기록','My choices')}</button></nav><a className="profile-link" href="/profile">{t('내 정보','My info')}</a><button className="language" onClick={()=>setLang(lang==='ko'?'en':'ko')}><Globe2 size={15}/>{lang==='ko'?'EN':'한국어'}</button></div></header>
 <main className={!showResults&&view==='today'?'choice-only':''}>{error&&<div className="error" role="alert">{error}<button onClick={()=>load()}><RefreshCw size={16}/>{t('다시 시도','Try again')}</button></div>}
 {!data&&!error&&<div className="loading" role="status"><Globe2 size={42}/><p>{t('오늘의 질문을 가져오고 있어요.','Finding today’s question.')}</p></div>}
 {data&&q&&view==='today'&&<>
 {!showResults&&<><div className="edition"><span>{t('하나의 질문, 수많은 생각','ONE QUESTION. MANY PERSPECTIVES.')}</span><span>{data.day.replaceAll('-','.')} · {t('전 세계 공통','WORLDWIDE')}</span></div>
 <section className="question"><div className="eyebrow"><span className="tag">{q.tag[i]}</span><span>{t('오늘의 선택','TODAY’S CHOICE')} / {String(((Math.floor(Date.parse(data.day)/86400000))%7)+1).padStart(2,'0')}</span></div><QuestionMood day={data.day}/><h1 id="question-heading" tabIndex={-1}>{q.title[i]}</h1><p className="question-intro">{t('정답은 없어요. 당신의 마음이 가는 쪽은?','No right answer. Which way does your heart lean?')}</p>
 <div className="choices">{[0,1].map(c=><button key={c} className={'choice side'+c+((data.own?.choice===c||(!data.own&&choice===c))?' selected':'')} aria-pressed={data.own?data.own.choice===c:choice===c} disabled={!!data.own||busy} onClick={()=>setChoice(c)}><Mascot side={c} badge className="choice-person"/><span className="choice-text"><strong>{q.options[c][i]}</strong><small>{q.sub[c][i]}</small></span><span className="choice-circle">{(data.own?.choice===c||(!data.own&&choice===c))&&<Check size={19}/>}</span></button>)}</div>
 {!data.own?<div className="vote-row"><span className="vote-region"><Globe2 size={16}/>{regions.find(r=>r[0]===country)?.[i+2]}</span><button className="primary" disabled={choice===null||busy} onClick={async()=>{if(await act({action:'vote',choice,country}))setResultsDay(data.day)}}>{busy?t('저장 중…','Saving…'):t('선택하고 세계의 답 보기','Choose & see the world')}</button><p>{t('투표 후, 당신이 고른 이유를 나눠보세요.','Vote first, then share the reason behind your choice.')}</p></div>:<div className="vote-row saved-choice-row"><span><Check size={17}/>{t('오늘은 이미 선택했어요.','You have already chosen today.')}</span><button className="primary" onClick={()=>setResultsDay(data.day)}>{t('내 선택 결과 보기','See my results')}</button></div>}
 </section></>}

 {showResults&&data.own&&<div className="results" id="world-results"><section className="world-result"><div className="section-heading"><div><span className="eyebrow">01 / THE WORLD</span><h1 className="result-title" id="results-heading" tabIndex={-1}>{t('같은 질문, 다른 선택','One question. Different choices.')}</h1></div><span className="participant"><Globe2 size={17}/>{total.toLocaleString()} {t('명 참여','votes')}</span></div><div className="result-numbers">{[0,1].map(c=><div className={'number side'+c} key={c}><div className="result-label"><Mascot side={c} badge/><span>{q.options[c][i]}</span></div><strong>{percent(c)}<small>%</small></strong>{data.own?.choice===c&&<em>{t('당신의 선택','YOUR CHOICE')}</em>}</div>)}</div><div className="result-bar" role="img" aria-label={`A ${percent(0)}%, B ${percent(1)}%`}><span style={{width:percent(0)+'%'}}/><span style={{width:percent(1)+'%'}}/></div><p className="sample-note">{t('서비스 참여자의 실제 응답입니다. 국가 전체를 대표하는 여론조사가 아닙니다.','Actual responses from participants, not a representative national survey.')}</p><div className="result-actions"><button onClick={()=>setResultsDay(null)}>{t('오늘의 질문 다시 보기','View today’s question')}</button><button onClick={share}><Share2 size={16}/>{t('친구에게 물어보기','Ask a friend')}</button></div>
 <div className="countries"><div className="section-heading compact"><h3>{t('국경을 넘으면, 생각도 달라질까?','Do perspectives change across borders?')}</h3><span>{t('A 선택 비율','Share choosing A')}</span></div>{regionRows.map(({r,n,p})=><div className="country-row" key={r[0]}><span>{r[1]} {r[i+2]}</span><div className="mini-track"><span style={{width:p+'%'}}/></div><strong>{p}%</strong><small>n={n}</small></div>)}{regionRows.length<2&&<div className="empty-inline">{t('다른 지역의 첫 선택을 기다리고 있어요.','Waiting for the first choice from another region.')}</div>}<p className="sample-note">{t('지역은 자기 보고 정보이며, 응답이 적을수록 비율이 쉽게 바뀝니다.','Regions are self-reported. Small samples can change quickly.')}</p></div></section>
 <Discussion key={data.day} day={data.day} lang={lang} ownChoice={data.own.choice} nickname={data.profile?.nickname||''} busy={busy} actionError={error} act={act} onToast={setToast}/>
 <section className="story"><span className="eyebrow">03 / BEYOND THE NUMBERS</span><h2>{t('숫자 뒤에 있는 이야기','The story behind the numbers')}</h2><p>{q.story[i]}</p><div className="knowledge"><Bookmark size={22}/><div><strong>{t('오늘의 생각 도구','A TOOL FOR TODAY')}</strong><p>{q.knowledge[i]}</p></div></div></section>
 <section className="both-sides"><div className="section-heading"><div><span className="eyebrow">04 / THE OTHER SIDE</span><h2>{t('어느 쪽에도, 이유는 있어요','There is a reason on both sides')}</h2></div></div><div className="argument-grid">{[0,1].map(c=><article className={'argument side'+c} key={c}><span className="argument-label"><Mascot side={c} badge/>{q.options[c][i]}</span><p>“{q.arguments[c][i]}”</p><small>{t('편집팀이 제시한 관점 · 실제 댓글 아님','An editorial perspective · not a user comment')}</small></article>)}</div><div className="rethink"><span>{t('조건 하나를 바꿔볼까요?','CHANGE ONE CONDITION')}</span><h3>{q.prompt[i]}</h3><p>{t('두 관점을 읽은 뒤, 처음 생각은 어떤가요?','After reading both sides, how do you feel about your first choice?')}</p><div>{[['same','그대로예요','Still the same'],['unsure','조금 흔들려요','A little unsure'],['changed','생각이 바뀌었어요','Changed my mind']].map(r=><button key={r[0]} aria-pressed={data.own?.reflection===r[0]} disabled={busy} onClick={()=>act({action:'reflection',value:r[0]})}>{data.own?.reflection===r[0]&&<Check size={15}/>} {r[i+1]}</button>)}</div><small>{t('처음 투표는 유지되고, 생각의 변화는 따로 기록돼요.','Your original vote stays. Your reflection is saved separately.')}</small></div></section>

 <section className="daily-you"><span className="eyebrow">05 / A LITTLE MORE YOU</span><div className="section-heading"><h2>{t('오늘 발견한 나','A little more you')}</h2><Sparkles size={27}/></div><blockquote>{q.insight[data.own.choice][i]}</blockquote><p>{t('오늘의 답을 설명하는 짧은 해석이에요. 성격 검사나 심리 진단은 아닙니다.','A short reading of today’s answer, not a personality test or diagnosis.')}</p><div className="progress-heading"><span>{history.length} / 7 {t('개의 선택','choices')}</span><span>{t('일주일의 나를 알아가는 중','Discovering a week of you')}</span></div><div className="progress-dots">{Array.from({length:7},(_,j)=><span key={j} className={j<history.length?'filled':''}>{j<history.length?<Check size={17}/>:j+1}</span>)}</div><button onClick={()=>{setView('history');window.scrollTo({top:0,behavior:'smooth'})}}>{t('내 선택 기록 보기','See my choices')}<Bookmark size={17}/></button></section>
 <section className="tomorrow"><span>{t('내일도, 나를 하나 더 발견해요.','Tomorrow, discover another side of you.')}</span><strong>{remaining}</strong><p>{t('다음 질문까지 · 매일 오전 9시 한국 시간 / UTC 00:00','Until the next question · daily at 00:00 UTC')}</p><button className="outline" onClick={share}><Share2 size={17}/>{t('오늘의 질문 공유하기','Share today’s question')}</button></section></div>}
 </>}
 {data&&view==='history'&&<section className="history-view"><span className="eyebrow">MY CHOICES</span><h1>{t('선택이 모이면, 내가 보여요.','Your choices tell a story.')}</h1><p>{t('하루에 하나씩, 당신이 남긴 생각들.','One a day. The perspectives you leave behind.')}</p><div className="history-stats"><div><strong>{history.length}</strong><span>{t('쌓인 선택','saved choices')}</span></div><div><strong>{streak}</strong><span>{t('일 연속 참여','day streak')}</span></div><div><strong>{history.filter(v=>v.reflection==='changed').length}</strong><span>{t('번 생각의 변화','changes of mind')}</span></div></div><div className="milestones">{[7,30].map(n=><div key={n}><Sparkles size={23}/><strong>{n}{t('개의 선택으로 보는 나',' choices of you')}</strong><p>{history.length>=n?t(`${n}개의 답이 쌓였어요. 서로 다른 상황에서 무엇을 골랐는지 기록을 비교해 보세요.`,`${n} answers saved. Compare your choices across different situations.`):t(`${n-history.length}개의 선택을 더 남기면 기록을 비교해 볼 수 있어요.`,`${n-history.length} more choices to compare your record.`)}</p><div className="milestone-track"><span style={{width:Math.min(history.length/n*100,100)+'%'}}/></div></div>)}</div>{history.length?history.map(v=>{const old=questionFor(v.day);return <article className="history-item" key={v.day}><time>{v.day}</time><h3>{old.title[i].replace('\n',' ')}</h3><span className={'history-pick side'+v.choice}>{v.choice===0?'A':'B'} · {old.options[v.choice][i]}</span><p>{old.insight[v.choice][i]}</p>{v.reflection&&<small>{t('읽은 뒤의 생각: ','After reading: ')}{v.reflection==='changed'?t('바뀌었어요','Changed'):v.reflection==='unsure'?t('조금 흔들려요','Unsure'):t('그대로예요','Same')}</small>}</article>}):<div className="empty-comments"><Bookmark size={27}/><h3>{t('오늘의 첫 선택을 남겨보세요.','Make your first choice today.')}</h3><button className="primary" onClick={()=>setView('today')}>{t('오늘의 질문','Today’s question')}</button></div>}<p className="sample-note">{t('기록은 로그인한 계정에 저장됩니다. 다른 기기에서도 같은 ChatGPT 계정으로 로그인하면 이어서 볼 수 있어요.','Records are saved to your signed-in account. Sign in with the same ChatGPT account on another device to see them.')}</p></section>}
 </main><footer><span className="footer-brand">{t('커뮤니티','COMMUNITY')}</span><p>{t('매일 하나의 질문으로, 세상과 나를 알아갑니다.','One question a day. A little more world. A little more you.')}</p><button onClick={()=>setAbout(true)}>{t('서비스 안내','About this preview')}</button><span>© 2026 COMMUNITY</span></footer>
 {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
 {about&&<div className="modal-backdrop" onClick={()=>setAbout(false)}><section className="modal" role="dialog" aria-modal="true" aria-label={t('서비스 안내','About')} onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setAbout(false)} aria-label="Close"><X/></button><span className="eyebrow">COMMUNITY / FIRST EDITION</span><h2>{t('세상과 나를 알아가는 작은 시작','A small beginning')}</h2><p>{t('매일 전 세계에 같은 질문을 보여줍니다. 현재는 7개의 편집 질문이 순환하는 첫 체험판입니다.','Everyone sees the same daily question. This first preview rotates through seven editorial questions.')}</p><p>{t('집계는 실제 참여 응답으로만 계산합니다. 국가는 본인이 선택하며, 모집단을 대표하지 않습니다. 예시 관점은 실제 댓글과 구분해 표시합니다.','Statistics use actual responses only. Regions are self-reported and results do not represent national populations. Editorial perspectives are labeled separately from user comments.')}</p><p>{t('댓글은 원문으로 표시합니다. 욕설 일부와 빠른 반복 작성을 제한하며, 신고한 글은 본인에게 숨겨집니다. 3명 이상 신고한 글은 전체에서 숨겨집니다.','Comments appear in their original language. Basic profanity and posting-rate limits apply. Reported comments are hidden from the reporter; three reports hide a comment for everyone.')}</p><p>{t('ChatGPT 계정으로 가입·로그인하고 프로필과 기록을 이어서 볼 수 있습니다. AI 심층 분석, 자동 번역, 구글·카카오 로그인, 결제와 광고는 다음 단계입니다. 현재는 무료 기능의 흐름을 검증하는 비공개 체험판입니다.','ChatGPT sign-in saves your profile and history across devices. AI analysis, automatic translation, Google/Kakao sign-in, payments and ads are future steps. This private preview tests the free core experience.')}</p><button className="primary" onClick={()=>setAbout(false)}>{t('알겠어요','Got it')}</button></section></div>}
 </>
}
