'use client';
import {useEffect,useState} from 'react';
import {Globe2,UserRound,MessageCircle,Bookmark,Check,LogOut,RefreshCw} from 'lucide-react';
import {regions,genders,ageGroups,type Profile} from '@/lib/community';
import {questionFor,type Question,type Lang} from '@/lib/questions';
import type {Member} from '@/lib/member';
import Mascot from '../mascot';
type OwnComment={id:string;day:string;choice:number;body:string;parent:string|null;created:string};
type Vote={day:string;choice:number;reflection:string|null};
type AccountData={profile:Profile|null;historyQuestions:Record<string,Question>;history:Vote[];comments:OwnComment[];stats:{votes:number;comments:number};nextCursor:string|null;error?:string};
const emptyProfile:Profile={nickname:'',country:'',gender:'',ageGroup:''};
export default function Account({member,signOutUrl}:{member:Member;signOutUrl:string}){
 const [lang,setLang]=useState<Lang>('ko'),[tab,setTab]=useState('profile'),[data,setData]=useState<AccountData|null>(null),[profile,setProfile]=useState<Profile>(emptyProfile),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirming,setConfirming]=useState(false),[confirmation,setConfirmation]=useState(''),[deleted,setDeleted]=useState(false);
 const i=lang==='ko'?0:1,t=(ko:string,en:string)=>i===0?ko:en;
 useEffect(()=>{if(localStorage.getItem('ow_lang')==='en')setLang('en');load()},[]);
 useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem('ow_lang',lang)},[lang]);
 async function load(more=false){setLoading(true);setError('');try{const r=await fetch('/api/account'+(more&&data?.nextCursor?'?cursor='+encodeURIComponent(data.nextCursor):''));const v=await r.json() as AccountData;if(!r.ok)throw Error(v.error);setData(old=>more&&old?{...v,historyQuestions:{...old.historyQuestions,...v.historyQuestions},comments:[...old.comments,...v.comments.filter(c=>!old.comments.some(x=>x.id===c.id))]}:v);if(!more)setProfile(v.profile||emptyProfile)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});const v=await r.json() as {profile:Profile;error?:string};if(!r.ok)throw Error(v.error);setProfile(v.profile);setData(old=>old?{...old,profile:v.profile}:old);setNotice(t('내 정보를 저장했어요.','Your profile is saved.'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function remove(){setBusy(true);setError('');try{const r=await fetch('/api/account',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:'DELETE_COMMUNITY_ACCOUNT'})});const v=await r.json() as {deleted?:boolean;error?:string};if(!r.ok)throw Error(v.error);setDeleted(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><header><div className="header-inner"><a className="brand" href="/"><span className="brand-icon"><Mascot/></span>{t('커뮤니티','COMMUNITY')}</a><a className="profile-link" href="/">{t('오늘의 질문','Today’s question')}</a><button className="language" onClick={()=>setLang(lang==='ko'?'en':'ko')}>{lang==='ko'?'EN':'한국어'}</button></div></header><main className="account-main">
 {deleted?<section className="account-card"><Check size={30}/><h1>{t('커뮤니티 탈퇴가 완료됐어요.','Your community account is deleted.')}</h1><p>{t('프로필과 투표 기록을 삭제했고, 작성한 댓글의 이름과 내용은 삭제 표시로 바꿨습니다. Google 계정은 그대로 유지됩니다.','Your profile and votes were removed, and your comments were replaced with deletion markers. Your Google account is unchanged.')}</p><a className="primary" href={signOutUrl} target="_top">{t('로그아웃하기','Sign out')}</a></section>:<>
 <div className="account-heading"><div><span className="eyebrow">MY COMMUNITY</span><h1>{t('내 커뮤니티','My community')}</h1><p>{profile.nickname||member.name}</p></div><a className="account-logout" href={signOutUrl} target="_top"><LogOut size={17}/>{t('로그아웃','Sign out')}</a></div>
 <div className="account-stats"><div><Bookmark size={20}/><strong>{data?.stats.votes??'—'}</strong><span>{t('나의 선택','My choices')}</span></div><div><MessageCircle size={20}/><strong>{data?.stats.comments??'—'}</strong><span>{t('내가 쓴 댓글','My comments')}</span></div></div>
 <div className="account-tabs" role="tablist" aria-label={t('내 계정 메뉴','Account menu')}>{[['profile','내 정보','Profile',UserRound],['comments','내 댓글','My comments',MessageCircle],['history','선택 기록','My choices',Bookmark]].map(([key,ko,en,Icon])=>{const K=Icon as typeof UserRound;return <button key={String(key)} role="tab" id={'tab-'+key} aria-selected={tab===key} aria-controls={'panel-'+key} className={tab===key?'selected':''} onClick={()=>{setTab(String(key));setNotice('')}}><K size={18}/>{i===0?String(ko):String(en)}</button>})}</div>
 {error&&<div className="error" role="alert">{error}{!data&&<button onClick={()=>load()}><RefreshCw size={16}/>{t('다시 시도','Retry')}</button>}</div>}
 {notice&&<p className="account-notice" role="status"><Check size={17}/>{notice}</p>}
 {loading&&!data&&<p className="comment-loading" role="status">{t('내 기록을 불러오는 중…','Loading your account…')}</p>}
 {data&&tab==='profile'&&<section className="account-card" id="panel-profile" role="tabpanel" aria-labelledby="tab-profile"><h2>{t('내 정보','Your profile')}</h2><p className="account-note">{t('정보는 로그인한 계정에 저장됩니다. 이메일·성별·나이대는 다른 회원에게 공개되지 않아요.','Your profile is saved to your account. Other members cannot see your email, gender or age group.')}</p><form onSubmit={save} className="account-form"><label>{t('로그인 계정','Signed-in account')}<input value={member.email} readOnly type="email"/></label><label>{t('닉네임','Nickname')}<input value={profile.nickname} onChange={e=>setProfile({...profile,nickname:e.target.value})} minLength={2} maxLength={24} autoComplete="nickname" required/><small>{t('완성된 한글·영문을 포함한 2–24자. 자음·모음만 있는 이름과 중복 닉네임은 사용할 수 없어요. 변경하면 기존 댓글에도 적용돼요.','Public on comments. Changes also update your past comments.')}</small></label><div className="account-selects"><label>{t('성별','Gender')}<select value={profile.gender} onChange={e=>setProfile({...profile,gender:e.target.value})} required><option value="" disabled>{t('선택','Choose')}</option>{genders.map(r=><option key={r[0]} value={r[0]}>{r[i+1]}</option>)}</select></label><label>{t('나이대','Age group')}<select value={profile.ageGroup} onChange={e=>setProfile({...profile,ageGroup:e.target.value})} required><option value="" disabled>{t('선택','Choose')}</option>{ageGroups.map(r=><option key={r[0]} value={r[0]}>{r[i+1]}</option>)}</select></label><label>{t('나라 / 지역','Country / region')}<select value={profile.country} onChange={e=>setProfile({...profile,country:e.target.value})} required><option value="" disabled>{t('선택','Choose')}</option>{regions.map(r=><option key={r[0]} value={r[0]}>{r[1]} {r[i+2]}</option>)}</select></label></div><p className="account-note">{t('지역 변경은 앞으로의 투표에 적용됩니다. 이전 투표의 지역은 유지돼요.','A new region applies to future votes. Previous votes keep their original region.')}</p><button className="primary" disabled={busy||profile.nickname.trim().length<2}>{busy?t('저장 중…','Saving…'):t('내 정보 저장','Save profile')}</button></form><div className="account-delete"><button onClick={()=>setConfirming(!confirming)} aria-expanded={confirming}>{t('커뮤니티 탈퇴','Delete community account')}</button>{confirming&&<div><p>{t('프로필·투표·공감 기록을 삭제합니다. 댓글의 이름과 내용은 삭제 표시로 바뀌고, 다른 회원의 답글은 유지됩니다. 복구할 수 없습니다.','Your profile, votes and reactions will be deleted. Your comment text and name will be removed while other members’ replies remain. This cannot be undone.')}</p><label>{t('확인하려면 “탈퇴”를 입력해 주세요.','Type DELETE to confirm.')}<input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></label><button className="danger" disabled={busy||confirmation!==(lang==='ko'?'탈퇴':'DELETE')} onClick={remove}>{busy?t('처리 중…','Deleting…'):t('내 커뮤니티 계정 삭제','Delete my community account')}</button></div>}</div></section>}
 {data&&tab==='comments'&&<section className="account-card" id="panel-comments" role="tabpanel" aria-labelledby="tab-comments"><h2>{t('내가 남긴 이유','The reasons I shared')}</h2>{data.comments.length?data.comments.map(c=><article className="own-comment" key={c.id}><span>{c.day} · {c.parent?t('답글','Reply'):t('댓글','Comment')} · {c.choice===0?'A':'B'}</span><h3>{(data.historyQuestions?.[c.day]||questionFor(c.day)).title[i].replace('\n',' ')}</h3><p>{c.body}</p></article>):<div className="empty-comments"><MessageCircle size={25}/><p>{t('아직 남긴 댓글이 없어요. 오늘의 선택에 대한 이유를 들려주세요.','No comments yet. Share the reason for today’s choice.')}</p><a className="primary" href="/">{t('오늘의 질문 보기','Today’s question')}</a></div>}{data.nextCursor&&<div className="comments-more"><button disabled={loading} onClick={()=>load(true)}>{loading?t('불러오는 중…','Loading…'):t('내 댓글 더보기','More comments')}</button></div>}</section>}
 {data&&tab==='history'&&<section className="account-card" id="panel-history" role="tabpanel" aria-labelledby="tab-history"><h2>{t('내 선택 기록','My choices')}</h2><p className="account-note">{t('최근 100개의 선택을 보여드려요.','Showing your latest 100 choices.')}</p>{data.history.length?data.history.map(v=><article className="own-comment" key={v.day}><span>{v.day}</span><h3>{(data.historyQuestions?.[v.day]||questionFor(v.day)).title[i].replace('\n',' ')}</h3><p className={'history-pick side'+v.choice}>{v.choice===0?'A':'B'} · {(data.historyQuestions?.[v.day]||questionFor(v.day)).options[v.choice][i]}</p>{v.reflection&&<small>{t('읽은 뒤의 생각: ','After reading: ')}{v.reflection==='changed'?t('바뀌었어요','Changed'):v.reflection==='unsure'?t('조금 흔들려요','Unsure'):t('그대로예요','Same')}</small>}</article>):<div className="empty-comments"><Bookmark size={25}/><p>{t('첫 번째 선택을 기다리고 있어요.','Your first choice is waiting.')}</p><a className="primary" href="/">{t('오늘의 질문 보기','Today’s question')}</a></div>}</section>}
 </>}
 </main></>
}
