import { env } from 'cloudflare:workers';
import { database } from '@/db';
export type GoogleUser={userId:string;displayName:string;email:string;fullName:string|null};
const SESSION='__Host-community-session', FLOW='__Host-community-oauth';
const config=()=>{const e=env as unknown as Record<string,string>;if(!e.GOOGLE_CLIENT_ID||!e.GOOGLE_CLIENT_SECRET||!e.APP_URL)throw new Error('Google login configuration missing');const url=new URL(e.APP_URL);if(url.protocol!=='https:'||url.pathname!=='/')throw new Error('Invalid APP_URL');return {id:e.GOOGLE_CLIENT_ID,secret:e.GOOGLE_CLIENT_SECRET,origin:url.origin}};
let ready:Promise<unknown>|undefined;
async function tables(){if(!ready)ready=database().batch([
 database().prepare('CREATE TABLE IF NOT EXISTS google_sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL, email TEXT NOT NULL, name TEXT, expires INTEGER NOT NULL)'),
 database().prepare('CREATE INDEX IF NOT EXISTS google_sessions_user ON google_sessions(user_id)'),
 database().prepare('CREATE TABLE IF NOT EXISTS google_oauth_states (state_hash TEXT PRIMARY KEY, browser_hash TEXT NOT NULL, verifier TEXT NOT NULL, nonce TEXT NOT NULL, return_to TEXT NOT NULL, expires INTEGER NOT NULL)')
]).catch(e=>{ready=undefined;throw e});await ready}
const bytes=(s:string)=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
const b64=(b:Uint8Array)=>btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const random=()=>b64(crypto.getRandomValues(new Uint8Array(32)));
const hash=async(s:string)=>b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))));
function cookie(header:string|null,name:string){return header?.split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='))?.slice(name.length+1)||''}
function setCookie(name:string,value:string,age:number){return `${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`}
export function safeReturn(value:string|null){if(!value||!value.startsWith('/')||value.startsWith('//'))return '/';try{const u=new URL(value,'https://app.local');return u.origin==='https://app.local'&&!u.pathname.startsWith('/api/auth/')?u.pathname+u.search+u.hash:'/'}catch{return '/'}}
function redirectTo(url:string,cookies:string[]=[]){const h=new Headers({'Location':url,'Cache-Control':'no-store'});cookies.forEach(c=>h.append('Set-Cookie',c));return new Response(null,{status:303,headers:h})}
export async function sessionUser(header:string|null):Promise<GoogleUser|null>{const token=cookie(header,SESSION);if(!/^[A-Za-z0-9_-]{43}$/.test(token))return null;await tables();const row=await database().prepare('SELECT user_id,email,name FROM google_sessions WHERE token_hash=? AND expires>?').bind(await hash(token),Date.now()).first<{user_id:string;email:string;name:string|null}>();return row?{userId:row.user_id,email:row.email,fullName:row.name,displayName:row.name||row.email}:null}
export async function beginGoogle(req:Request){try{const c=config();await tables();const state=random(),browser=random(),verifier=random(),nonce=random(),now=Date.now();await database().batch([
 database().prepare('DELETE FROM google_oauth_states WHERE expires<=?').bind(now),database().prepare('DELETE FROM google_sessions WHERE expires<=?').bind(now),
 database().prepare('INSERT INTO google_oauth_states VALUES (?,?,?,?,?,?)').bind(await hash(state),await hash(browser),verifier,nonce,safeReturn(new URL(req.url).searchParams.get('return_to')),now+600000)
]);const u=new URL('https://accounts.google.com/o/oauth2/v2/auth');u.search=new URLSearchParams({client_id:c.id,redirect_uri:c.origin+'/api/auth/google/callback',response_type:'code',scope:'openid email profile',state,nonce,code_challenge:await hash(verifier),code_challenge_method:'S256',prompt:'select_account'}).toString();return redirectTo(u.href,[setCookie(FLOW,browser,600)])}catch{return new Response('구글 로그인 설정을 확인해 주세요.',{status:503,headers:{'Cache-Control':'no-store'}})}}
export async function finishGoogle(req:Request){const clear=setCookie(FLOW,'',0);try{const c=config(),u=new URL(req.url),state=u.searchParams.get('state')||'',browser=cookie(req.headers.get('cookie'),FLOW);if(!/^[A-Za-z0-9_-]{43}$/.test(state)||!/^[A-Za-z0-9_-]{43}$/.test(browser))throw Error();await tables();const flow=await database().prepare('DELETE FROM google_oauth_states WHERE state_hash=? AND browser_hash=? AND expires>? RETURNING verifier,nonce,return_to').bind(await hash(state),await hash(browser),Date.now()).first<{verifier:string;nonce:string;return_to:string}>();if(!flow)throw Error();if(u.searchParams.has('error'))return redirectTo(c.origin+'/?login_error=cancelled',[clear]);const code=u.searchParams.get('code');if(!code)throw Error();const res=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.id,client_secret:c.secret,code,code_verifier:flow.verifier,grant_type:'authorization_code',redirect_uri:c.origin+'/api/auth/google/callback'}),signal:AbortSignal.timeout(10000)});if(!res.ok)throw Error();const token=await res.json() as {id_token?:string};if(!token.id_token)throw Error();
// The ID token is received directly from Google's HTTPS token endpoint using our
// client secret. Google documents that TLS authenticates this code-flow response.
const parts=token.id_token.split('.');if(parts.length!==3)throw Error();const p=JSON.parse(new TextDecoder().decode(bytes(parts[1]))) as Record<string,unknown>;const now=Math.floor(Date.now()/1000);if(!['https://accounts.google.com','accounts.google.com'].includes(String(p.iss))||p.aud!==c.id||(p.azp!==undefined&&p.azp!==c.id)||p.nonce!==flow.nonce||typeof p.exp!=='number'||p.exp<=now||typeof p.iat!=='number'||p.iat>now+60||typeof p.sub!=='string'||!p.sub||typeof p.email!=='string'||p.email_verified!==true)throw Error();const session=random();await database().prepare('INSERT INTO google_sessions VALUES (?,?,?,?,?)').bind(await hash(session),'google:'+p.sub,p.email,typeof p.name==='string'?p.name:null,Date.now()+30*86400000).run();return redirectTo(c.origin+safeReturn(flow.return_to),[clear,setCookie(SESSION,session,30*86400)])}catch{return redirectTo('/?login_error=failed',[clear])}}
export async function endGoogle(req:Request){const token=cookie(req.headers.get('cookie'),SESSION);if(token){await tables();await database().prepare('DELETE FROM google_sessions WHERE token_hash=?').bind(await hash(token)).run()}return redirectTo(config().origin+safeReturn(new URL(req.url).searchParams.get('return_to')),[setCookie(SESSION,'',0),setCookie(FLOW,'',0)])}
