import {database} from '@/db';
const encode=(value:Uint8Array)=>btoa(String.fromCharCode(...value)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
export function decode(value:string){return Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0))}
const bytes=(value:string)=>new TextEncoder().encode(value);
const join=(...parts:Uint8Array[])=>{const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let at=0;for(const p of parts){out.set(p,at);at+=p.length}return out};
const source=(value:Uint8Array)=>value as BufferSource;
let ready:Promise<void>|undefined;
export function pushTables(){return ready??=(async()=>{await database().batch([
 database().prepare('CREATE TABLE IF NOT EXISTS push_settings(id TEXT PRIMARY KEY,value TEXT NOT NULL)'),
 database().prepare('CREATE TABLE IF NOT EXISTS push_devices(id TEXT PRIMARY KEY,user TEXT NOT NULL,endpoint TEXT NOT NULL,p256dh TEXT NOT NULL,auth TEXT NOT NULL,updated TEXT NOT NULL)'),
 database().prepare('CREATE INDEX IF NOT EXISTS push_user ON push_devices(user)'),
 database().prepare('CREATE TABLE IF NOT EXISTS push_limits(user TEXT PRIMARY KEY,last INTEGER NOT NULL)'),
 database().prepare('CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,user TEXT NOT NULL,comment TEXT NOT NULL,root TEXT NOT NULL,day TEXT NOT NULL,created TEXT NOT NULL,seen INTEGER NOT NULL DEFAULT 0)'),
 database().prepare('CREATE INDEX IF NOT EXISTS notifications_user ON notifications(user,created)')
 ]);})().catch(e=>{ready=undefined;throw e})}
let keyPromise:Promise<JsonWebKey>|undefined;
export function vapidKey(){return keyPromise??=(async()=>{await pushTables();const db=database();let row=await db.prepare("SELECT value FROM push_settings WHERE id='vapid'").first<{value:string}>();if(!row){const key=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);const jwk=await crypto.subtle.exportKey('jwk',key.privateKey);await db.prepare("INSERT INTO push_settings(id,value) VALUES ('vapid',?) ON CONFLICT(id) DO NOTHING").bind(JSON.stringify(jwk)).run();row=await db.prepare("SELECT value FROM push_settings WHERE id='vapid'").first<{value:string}>()}if(!row)throw Error('Push signing key unavailable');return JSON.parse(row.value) as JsonWebKey})().catch(e=>{keyPromise=undefined;throw e})}
export function publicKey(jwk:JsonWebKey){if(!jwk.x||!jwk.y)throw Error('Invalid signing key');return encode(join(new Uint8Array([4]),decode(jwk.x),decode(jwk.y)))}
export function validEndpoint(endpoint:unknown):endpoint is string{if(typeof endpoint!=='string'||endpoint.length>2048)return false;try{const u=new URL(endpoint);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&!u.hash&&(u.hostname==='fcm.googleapis.com'||u.hostname==='updates.push.services.mozilla.com'||u.hostname==='web.push.apple.com'||u.hostname.endsWith('.push.apple.com')||u.hostname==='wns.windows.com'||u.hostname.endsWith('.notify.windows.com'))}catch{return false}}
export function validSubscription(value:unknown):value is {endpoint:string;keys:{p256dh:string;auth:string}}{try{const v=value as {endpoint:string;keys:{p256dh:string;auth:string}};if(!validEndpoint(v.endpoint)||!v.keys||!/^[-\w]+$/.test(v.keys.p256dh)||!/^[-\w]+$/.test(v.keys.auth))return false;const key=decode(v.keys.p256dh);return key.length===65&&key[0]===4&&decode(v.keys.auth).length===16}catch{return false}}
export async function deviceId(endpoint:string){return encode(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes(endpoint))))}
export async function vapidAuthorization(endpoint:string,jwk:JsonWebKey){const key=await crypto.subtle.importKey('jwk',jwk,{name:'ECDSA',namedCurve:'P-256'},false,['sign']);const head=encode(bytes(JSON.stringify({typ:'JWT',alg:'ES256'}))),body=encode(bytes(JSON.stringify({aud:new URL(endpoint).origin,exp:Math.floor(Date.now()/1000)+3600,sub:'mailto:ssssshw207@gmail.com'})));const token=head+'.'+body;const signature=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,bytes(token));return `vapid t=${token}.${encode(new Uint8Array(signature))}, k=${publicKey(jwk)}`}
async function hmac(key:Uint8Array,value:Uint8Array){const imported=await crypto.subtle.importKey('raw',source(key),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',imported,source(value)))}
// Single final aes128gcm record, RFC 8291 / RFC 8188. Ephemeral encryption keys differ from VAPID signing keys.
export async function encryptPush(payload:string,subscription:{keys:{p256dh:string;auth:string}},salt=crypto.getRandomValues(new Uint8Array(16)),ephemeral?:CryptoKeyPair){const ua=decode(subscription.keys.p256dh),auth=decode(subscription.keys.auth);const peer=await crypto.subtle.importKey('raw',source(ua),{name:'ECDH',namedCurve:'P-256'},false,[]);const pair=ephemeral||await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);const server=new Uint8Array(await crypto.subtle.exportKey('raw',pair.publicKey));const shared=new Uint8Array(await crypto.subtle.deriveBits({name:'ECDH',public:peer},pair.privateKey,256));const prkKey=await hmac(auth,shared);const ikm=await hmac(prkKey,join(bytes('WebPush: info\0'),ua,server,new Uint8Array([1])));const prk=await hmac(salt,ikm);const cek=(await hmac(prk,join(bytes('Content-Encoding: aes128gcm\0'),new Uint8Array([1])))).slice(0,16);const nonce=(await hmac(prk,join(bytes('Content-Encoding: nonce\0'),new Uint8Array([1])))).slice(0,12);const text=bytes(payload);if(text.length>3900)throw Error('Push message too large');const aes=await crypto.subtle.importKey('raw',source(cek),'AES-GCM',false,['encrypt']);const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv:source(nonce)},aes,source(join(text,new Uint8Array([2]))));return join(salt,new Uint8Array([0,0,16,0,65]),server,new Uint8Array(encrypted))}
export async function sendToUser(user:string,payload:{title:string;body:string;url:string;tag:string}){await pushTables();const db=database(),jwk=await vapidKey();const rows=await db.prepare('SELECT id,endpoint,p256dh,auth FROM push_devices WHERE user=? ORDER BY updated DESC LIMIT 5').bind(user).all<{id:string;endpoint:string;p256dh:string;auth:string}>();const result=await Promise.all(rows.results.map(async device=>{if(!validEndpoint(device.endpoint))return false;try{const authorization=await vapidAuthorization(device.endpoint,jwk);const body=await encryptPush(JSON.stringify(payload),{keys:device});const response=await fetch(device.endpoint,{method:'POST',redirect:'error',headers:{Authorization:authorization,TTL:'3600',Urgency:'normal','Content-Encoding':'aes128gcm','Content-Type':'application/octet-stream'},body:source(body) as ArrayBuffer,signal:AbortSignal.timeout(5000)});if(response.status===404||response.status===410)await db.prepare('DELETE FROM push_devices WHERE id=? AND user=?').bind(device.id,user).run();return response.ok}catch{return false}}));return {accepted:result.filter(Boolean).length,total:result.length}}
export async function notifyReply(author:string,comment:string,root:string,day:string){await pushTables();const db=database();const parent=await db.prepare("SELECT user FROM comments WHERE id=? AND parent IS NULL AND user NOT LIKE 'deleted:%'").bind(root).first<{user:string}>();if(!parent||parent.user===author)return;const id=crypto.randomUUID();await db.prepare('INSERT INTO notifications(id,user,comment,root,day,created) VALUES (?,?,?,?,?,?)').bind(id,parent.user,comment,root,day,new Date().toISOString()).run();await db.prepare("DELETE FROM notifications WHERE created<?").bind(new Date(Date.now()-90*86400000).toISOString()).run();await sendToUser(parent.user,{title:'커뮤니티 · 새 답글',body:'내 의견에 새로운 답글이 달렸어요. 어떤 생각인지 확인해 보세요.',url:'/thread?id='+encodeURIComponent(root),tag:'reply-'+root})}
