import {database} from '@/db';
import {memberKey} from '@/lib/member';
import {pushTables,vapidKey,publicKey,validSubscription,deviceId,sendToUser} from '@/lib/push';
export const dynamic='force-dynamic';
const answer=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(req:Request){try{const user=await memberKey(req);return answer({signedIn:!!user,publicKey:publicKey(await vapidKey())})}catch{return answer({error:'알림 정보를 불러오지 못했어요.'},503)}}
export async function POST(req:Request){try{const user=await memberKey(req);if(!user)return answer({error:'구글 로그인 후 알림을 켜 주세요.'},401);if(req.headers.get('origin')!==new URL(req.url).origin)return answer({error:'잘못된 요청 출처입니다.'},403);const text=await req.text();if(text.length>8000)return answer({error:'요청이 너무 큽니다.'},413);const body=JSON.parse(text);await pushTables();const db=database();
 if(body.action==='test'){const now=Date.now();const allowed=await db.prepare('INSERT INTO push_limits(user,last) VALUES (?,?) ON CONFLICT(user) DO UPDATE SET last=excluded.last WHERE last<=? RETURNING user').bind(user,now,now-60000).first();if(!allowed)return answer({error:'1분 뒤 다시 테스트해 주세요.'},429);const result=await sendToUser(user,{title:'커뮤니티 알림 연결 완료',body:'이제 내 댓글에 답글이 달리면 알려드릴게요.',url:'/',tag:'community-test'});return Response.json({ok:result.accepted>0,...result,error:result.accepted?'':'전송에 실패했어요. 알림을 다시 연결해 주세요.'},{status:result.accepted?200:503,headers:{'Cache-Control':'no-store','Set-Cookie':'community-push-test=1; Max-Age=60; Path=/api/push; Secure; HttpOnly; SameSite=Lax'}})}
 if(body.action!=='subscribe'&&body.action!=='unsubscribe'&&body.action!=='status')return answer({error:'알 수 없는 작업입니다.'},400);if(!validSubscription(body.subscription))return answer({error:'이 브라우저의 알림 주소가 올바르지 않아요.'},400);const s=body.subscription,id=await deviceId(s.endpoint);if(body.action==='status')return answer({active:!!await db.prepare('SELECT id FROM push_devices WHERE id=? AND user=?').bind(id,user).first()});if(body.action==='unsubscribe'){await db.prepare('DELETE FROM push_devices WHERE id=? AND user=?').bind(id,user).run();return answer({ok:true})}
 await crypto.subtle.importKey('raw',Uint8Array.from(atob(s.keys.p256dh.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)),{name:'ECDH',namedCurve:'P-256'},false,[]);
 await db.prepare('INSERT INTO push_devices(id,user,endpoint,p256dh,auth,updated) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET user=excluded.user,p256dh=excluded.p256dh,auth=excluded.auth,updated=excluded.updated').bind(id,user,s.endpoint,s.keys.p256dh,s.keys.auth,new Date().toISOString()).run();await db.prepare('DELETE FROM push_devices WHERE user=? AND id NOT IN (SELECT id FROM push_devices WHERE user=? ORDER BY updated DESC LIMIT 5)').bind(user,user).run();return Response.json({ok:true},{headers:{'Cache-Control':'no-store','Set-Cookie':`community-push-device=${id}; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=2592000`}})
 }catch{return answer({error:'알림 설정을 저장하지 못했어요. 다시 시도해 주세요.'},503)}}
