import {topicBank} from '@/lib/topic-bank';
import {database} from '@/db';
import {adminTables,adminUser,calendarDay} from '@/lib/admin';
import {currentDay,questions} from '@/lib/questions';
import {parseQuestion,validDay,topicFor} from '@/lib/topic-store';
export const dynamic='force-dynamic';
function respond(value:unknown,status=200){return Response.json(value,{status,headers:{'Cache-Control':'no-store'}})}
export async function GET(req:Request){try{
 if(!await adminUser(req))return respond({error:'관리자 계정으로 로그인해 주세요.'},403);await adminTables();const db=database(),url=new URL(req.url),section=url.searchParams.get('section');
 if(section==='comments'){const filter=url.searchParams.get('filter')||'all',before=url.searchParams.get('before');const where=filter==='reported'?"AND (SELECT COUNT(*) FROM reactions r WHERE r.comment=c.id AND r.kind='report')>0":filter==='hidden'?'AND EXISTS(SELECT 1 FROM admin_hidden h WHERE h.comment=c.id)':'';const rows=await db.prepare(`SELECT c.id,c.day,c.name,c.body,c.parent,c.choice,c.created,EXISTS(SELECT 1 FROM admin_hidden h WHERE h.comment=c.id) AS hidden,(SELECT COUNT(*) FROM reactions r WHERE r.comment=c.id AND r.kind='report') AS reports FROM comments c WHERE c.user NOT LIKE 'deleted:%' ${where} ${before?'AND (c.created<? OR (c.created=? AND c.id<?))':''} ORDER BY c.created DESC,c.id DESC LIMIT 21`).bind(...(before?(()=>{const v=JSON.parse(before);if(typeof v.created!=='string'||typeof v.id!=='string'||v.id.length>60)throw Error('Invalid cursor');return [v.created,v.created,v.id]})():[])).all<{id:string;created:string}>();const items=rows.results.slice(0,20),last=items[items.length-1];return respond({items,next:rows.results.length>20?JSON.stringify({created:last.created,id:last.id}):null})}
 const today=calendarDay(),start=calendarDay(new Date(Date.now()-13*86400000));const [counts,visits,votes,comments,plans,current]=await Promise.all([
 db.prepare('SELECT (SELECT COUNT(*) FROM profiles) AS members,(SELECT COUNT(DISTINCT user) FROM votes) AS voters,(SELECT COUNT(*) FROM votes) AS votes,(SELECT COUNT(*) FROM comments WHERE user NOT LIKE \'deleted:%\') AS comments,(SELECT COUNT(DISTINCT comment) FROM reactions WHERE kind=\'report\') AS reported,(SELECT COUNT(*) FROM admin_hidden) AS hidden').first(),
 db.prepare('SELECT day,COUNT(*) AS visitors,SUM(views) AS views FROM visit_days WHERE day>=? GROUP BY day ORDER BY day').bind(start).all(),
 db.prepare("SELECT date(created,'+9 hours') AS day,COUNT(*) AS votes FROM votes WHERE date(created,'+9 hours')>=? GROUP BY day").bind(start).all(),
 db.prepare("SELECT date(created,'+9 hours') AS day,COUNT(*) AS comments FROM comments WHERE date(created,'+9 hours')>=? AND user NOT LIKE 'deleted:%' GROUP BY day").bind(start).all(),
 db.prepare('SELECT day,question,image FROM scheduled_questions WHERE day>=? ORDER BY day LIMIT 180').bind(currentDay()).all<{day:string;question:string;image:string}>(),topicFor(currentDay())
 ]);return respond({counts,today,start,visits:visits.results,dailyVotes:votes.results,dailyComments:comments.results,currentDay:currentDay(),current,templates:[...questions,...topicBank.map(t=>t.question)],templateImages:[...questions.map((_,i)=>`/images/topic-${i}.webp`),...topicBank.map(t=>t.image)],plans:plans.results.map(p=>({...p,question:JSON.parse(p.question)}))});
 }catch(e){console.error('admin read failed',e);return respond({error:'관리 화면을 불러오지 못했습니다. 다시 시도해 주세요.'},503)}}
export async function POST(req:Request){try{
 if(!await adminUser(req))return respond({error:'관리자 권한이 필요합니다.'},403);if(req.headers.get('origin')!==new URL(req.url).origin)return respond({error:'요청 출처가 올바르지 않습니다.'},403);const text=await req.text();if(text.length>32000)return respond({error:'입력 내용이 너무 깁니다.'},413);const body=JSON.parse(text);await adminTables();const db=database();
 if(body.action==='hide'||body.action==='restore'){if(typeof body.id!=='string'||body.id.length>60)return respond({error:'잘못된 댓글입니다.'},400);const exists=await db.prepare('SELECT id FROM comments WHERE id=?').bind(body.id).first();if(!exists)return respond({error:'댓글을 찾을 수 없습니다.'},404);if(body.action==='hide')await db.prepare('INSERT INTO admin_hidden(comment,updated) VALUES (?,?) ON CONFLICT(comment) DO UPDATE SET updated=excluded.updated').bind(body.id,new Date().toISOString()).run();else await db.prepare('DELETE FROM admin_hidden WHERE comment=?').bind(body.id).run();return respond({ok:true})}
 if(body.action==='schedule'||body.action==='cancel'){if(!validDay(body.day)||body.day<=currentDay()||body.day>new Date(Date.now()+180*86400000).toISOString().slice(0,10))return respond({error:'내일부터 180일 이내 날짜를 선택해 주세요. 공개된 질문은 변경할 수 없습니다.'},400);if(await db.prepare('SELECT day FROM question_days WHERE day=?').bind(body.day).first())return respond({error:'이미 공개된 질문은 변경할 수 없습니다.'},409);
 if(body.action==='cancel')await db.prepare('DELETE FROM scheduled_questions WHERE day=? AND day>?').bind(body.day,currentDay()).run();else {const question=parseQuestion(body.question);if(!question||typeof body.image!=='string'||!(/^\/images\/topic-[0-6]\.webp$/.test(body.image)||topicBank.some(t=>t.image===body.image)))return respond({error:'질문·선택지·설명을 한국어와 영어 모두 작성해 주세요.'},400);await db.prepare('INSERT INTO scheduled_questions(day,question,image) SELECT ?,?,? WHERE ?>? ON CONFLICT(day) DO UPDATE SET question=excluded.question,image=excluded.image').bind(body.day,JSON.stringify(question),body.image,body.day,currentDay()).run()}return respond({ok:true})}
 return respond({error:'알 수 없는 작업입니다.'},400);
 }catch(e){console.error('admin write failed',e);return respond({error:'저장하지 못했습니다. 입력 내용을 확인하고 다시 시도해 주세요.'},503)}}
